// GENERATED by scripts/gen_program.py --emit -- DO NOT EDIT
// Per-op geometry and golden vectors for accel_tb.
//
// Include this INSIDE the module, after gold_mem is declared:
//     `include "program_ops.svh"
// then call load_op_table once before using the arrays.

localparam integer N_PROG_OPS = 64;

integer OP_OPCODE [0:N_PROG_OPS-1];
integer OP_OC [0:N_PROG_OPS-1];
integer OP_IC [0:N_PROG_OPS-1];
integer OP_OH [0:N_PROG_OPS-1];
integer OP_OW [0:N_PROG_OPS-1];

task automatic load_op_table;
    begin
        OP_OPCODE[0]=1; OP_OC[0]=32; OP_IC[0]=3; OP_OH[0]=112; OP_OW[0]=112;  // STEM features.0.0
        OP_OPCODE[1]=3; OP_OC[1]=32; OP_IC[1]=32; OP_OH[1]=112; OP_OW[1]=112;  // DW features.1.conv.0.0
        OP_OPCODE[2]=2; OP_OC[2]=16; OP_IC[2]=32; OP_OH[2]=112; OP_OW[2]=112;  // PW features.1.conv.1
        OP_OPCODE[3]=2; OP_OC[3]=96; OP_IC[3]=16; OP_OH[3]=112; OP_OW[3]=112;  // PW features.2.conv.0.0
        OP_OPCODE[4]=3; OP_OC[4]=96; OP_IC[4]=96; OP_OH[4]=56; OP_OW[4]=56;  // DW features.2.conv.1.0
        OP_OPCODE[5]=2; OP_OC[5]=24; OP_IC[5]=96; OP_OH[5]=56; OP_OW[5]=56;  // PW features.2.conv.2
        OP_OPCODE[6]=2; OP_OC[6]=144; OP_IC[6]=24; OP_OH[6]=56; OP_OW[6]=56;  // PW features.3.conv.0.0
        OP_OPCODE[7]=3; OP_OC[7]=144; OP_IC[7]=144; OP_OH[7]=56; OP_OW[7]=56;  // DW features.3.conv.1.0
        OP_OPCODE[8]=2; OP_OC[8]=24; OP_IC[8]=144; OP_OH[8]=56; OP_OW[8]=56;  // PW features.3.conv.2
        OP_OPCODE[9]=4; OP_OC[9]=24; OP_IC[9]=24; OP_OH[9]=56; OP_OW[9]=56;  // RES_ADD features.3.add
        OP_OPCODE[10]=2; OP_OC[10]=144; OP_IC[10]=24; OP_OH[10]=56; OP_OW[10]=56;  // PW features.4.conv.0.0
        OP_OPCODE[11]=3; OP_OC[11]=144; OP_IC[11]=144; OP_OH[11]=28; OP_OW[11]=28;  // DW features.4.conv.1.0
        OP_OPCODE[12]=2; OP_OC[12]=32; OP_IC[12]=144; OP_OH[12]=28; OP_OW[12]=28;  // PW features.4.conv.2
        OP_OPCODE[13]=2; OP_OC[13]=192; OP_IC[13]=32; OP_OH[13]=28; OP_OW[13]=28;  // PW features.5.conv.0.0
        OP_OPCODE[14]=3; OP_OC[14]=192; OP_IC[14]=192; OP_OH[14]=28; OP_OW[14]=28;  // DW features.5.conv.1.0
        OP_OPCODE[15]=2; OP_OC[15]=32; OP_IC[15]=192; OP_OH[15]=28; OP_OW[15]=28;  // PW features.5.conv.2
        OP_OPCODE[16]=4; OP_OC[16]=32; OP_IC[16]=32; OP_OH[16]=28; OP_OW[16]=28;  // RES_ADD features.5.add
        OP_OPCODE[17]=2; OP_OC[17]=192; OP_IC[17]=32; OP_OH[17]=28; OP_OW[17]=28;  // PW features.6.conv.0.0
        OP_OPCODE[18]=3; OP_OC[18]=192; OP_IC[18]=192; OP_OH[18]=28; OP_OW[18]=28;  // DW features.6.conv.1.0
        OP_OPCODE[19]=2; OP_OC[19]=32; OP_IC[19]=192; OP_OH[19]=28; OP_OW[19]=28;  // PW features.6.conv.2
        OP_OPCODE[20]=4; OP_OC[20]=32; OP_IC[20]=32; OP_OH[20]=28; OP_OW[20]=28;  // RES_ADD features.6.add
        OP_OPCODE[21]=2; OP_OC[21]=192; OP_IC[21]=32; OP_OH[21]=28; OP_OW[21]=28;  // PW features.7.conv.0.0
        OP_OPCODE[22]=3; OP_OC[22]=192; OP_IC[22]=192; OP_OH[22]=14; OP_OW[22]=14;  // DW features.7.conv.1.0
        OP_OPCODE[23]=2; OP_OC[23]=64; OP_IC[23]=192; OP_OH[23]=14; OP_OW[23]=14;  // PW features.7.conv.2
        OP_OPCODE[24]=2; OP_OC[24]=384; OP_IC[24]=64; OP_OH[24]=14; OP_OW[24]=14;  // PW features.8.conv.0.0
        OP_OPCODE[25]=3; OP_OC[25]=384; OP_IC[25]=384; OP_OH[25]=14; OP_OW[25]=14;  // DW features.8.conv.1.0
        OP_OPCODE[26]=2; OP_OC[26]=64; OP_IC[26]=384; OP_OH[26]=14; OP_OW[26]=14;  // PW features.8.conv.2
        OP_OPCODE[27]=4; OP_OC[27]=64; OP_IC[27]=64; OP_OH[27]=14; OP_OW[27]=14;  // RES_ADD features.8.add
        OP_OPCODE[28]=2; OP_OC[28]=384; OP_IC[28]=64; OP_OH[28]=14; OP_OW[28]=14;  // PW features.9.conv.0.0
        OP_OPCODE[29]=3; OP_OC[29]=384; OP_IC[29]=384; OP_OH[29]=14; OP_OW[29]=14;  // DW features.9.conv.1.0
        OP_OPCODE[30]=2; OP_OC[30]=64; OP_IC[30]=384; OP_OH[30]=14; OP_OW[30]=14;  // PW features.9.conv.2
        OP_OPCODE[31]=4; OP_OC[31]=64; OP_IC[31]=64; OP_OH[31]=14; OP_OW[31]=14;  // RES_ADD features.9.add
        OP_OPCODE[32]=2; OP_OC[32]=384; OP_IC[32]=64; OP_OH[32]=14; OP_OW[32]=14;  // PW features.10.conv.0.0
        OP_OPCODE[33]=3; OP_OC[33]=384; OP_IC[33]=384; OP_OH[33]=14; OP_OW[33]=14;  // DW features.10.conv.1.0
        OP_OPCODE[34]=2; OP_OC[34]=64; OP_IC[34]=384; OP_OH[34]=14; OP_OW[34]=14;  // PW features.10.conv.2
        OP_OPCODE[35]=4; OP_OC[35]=64; OP_IC[35]=64; OP_OH[35]=14; OP_OW[35]=14;  // RES_ADD features.10.add
        OP_OPCODE[36]=2; OP_OC[36]=384; OP_IC[36]=64; OP_OH[36]=14; OP_OW[36]=14;  // PW features.11.conv.0.0
        OP_OPCODE[37]=3; OP_OC[37]=384; OP_IC[37]=384; OP_OH[37]=14; OP_OW[37]=14;  // DW features.11.conv.1.0
        OP_OPCODE[38]=2; OP_OC[38]=96; OP_IC[38]=384; OP_OH[38]=14; OP_OW[38]=14;  // PW features.11.conv.2
        OP_OPCODE[39]=2; OP_OC[39]=576; OP_IC[39]=96; OP_OH[39]=14; OP_OW[39]=14;  // PW features.12.conv.0.0
        OP_OPCODE[40]=3; OP_OC[40]=576; OP_IC[40]=576; OP_OH[40]=14; OP_OW[40]=14;  // DW features.12.conv.1.0
        OP_OPCODE[41]=2; OP_OC[41]=96; OP_IC[41]=576; OP_OH[41]=14; OP_OW[41]=14;  // PW features.12.conv.2
        OP_OPCODE[42]=4; OP_OC[42]=96; OP_IC[42]=96; OP_OH[42]=14; OP_OW[42]=14;  // RES_ADD features.12.add
        OP_OPCODE[43]=2; OP_OC[43]=576; OP_IC[43]=96; OP_OH[43]=14; OP_OW[43]=14;  // PW features.13.conv.0.0
        OP_OPCODE[44]=3; OP_OC[44]=576; OP_IC[44]=576; OP_OH[44]=14; OP_OW[44]=14;  // DW features.13.conv.1.0
        OP_OPCODE[45]=2; OP_OC[45]=96; OP_IC[45]=576; OP_OH[45]=14; OP_OW[45]=14;  // PW features.13.conv.2
        OP_OPCODE[46]=4; OP_OC[46]=96; OP_IC[46]=96; OP_OH[46]=14; OP_OW[46]=14;  // RES_ADD features.13.add
        OP_OPCODE[47]=2; OP_OC[47]=576; OP_IC[47]=96; OP_OH[47]=14; OP_OW[47]=14;  // PW features.14.conv.0.0
        OP_OPCODE[48]=3; OP_OC[48]=576; OP_IC[48]=576; OP_OH[48]=7; OP_OW[48]=7;  // DW features.14.conv.1.0
        OP_OPCODE[49]=2; OP_OC[49]=160; OP_IC[49]=576; OP_OH[49]=7; OP_OW[49]=7;  // PW features.14.conv.2
        OP_OPCODE[50]=2; OP_OC[50]=960; OP_IC[50]=160; OP_OH[50]=7; OP_OW[50]=7;  // PW features.15.conv.0.0
        OP_OPCODE[51]=3; OP_OC[51]=960; OP_IC[51]=960; OP_OH[51]=7; OP_OW[51]=7;  // DW features.15.conv.1.0
        OP_OPCODE[52]=2; OP_OC[52]=160; OP_IC[52]=960; OP_OH[52]=7; OP_OW[52]=7;  // PW features.15.conv.2
        OP_OPCODE[53]=4; OP_OC[53]=160; OP_IC[53]=160; OP_OH[53]=7; OP_OW[53]=7;  // RES_ADD features.15.add
        OP_OPCODE[54]=2; OP_OC[54]=960; OP_IC[54]=160; OP_OH[54]=7; OP_OW[54]=7;  // PW features.16.conv.0.0
        OP_OPCODE[55]=3; OP_OC[55]=960; OP_IC[55]=960; OP_OH[55]=7; OP_OW[55]=7;  // DW features.16.conv.1.0
        OP_OPCODE[56]=2; OP_OC[56]=160; OP_IC[56]=960; OP_OH[56]=7; OP_OW[56]=7;  // PW features.16.conv.2
        OP_OPCODE[57]=4; OP_OC[57]=160; OP_IC[57]=160; OP_OH[57]=7; OP_OW[57]=7;  // RES_ADD features.16.add
        OP_OPCODE[58]=2; OP_OC[58]=960; OP_IC[58]=160; OP_OH[58]=7; OP_OW[58]=7;  // PW features.17.conv.0.0
        OP_OPCODE[59]=3; OP_OC[59]=960; OP_IC[59]=960; OP_OH[59]=7; OP_OW[59]=7;  // DW features.17.conv.1.0
        OP_OPCODE[60]=2; OP_OC[60]=320; OP_IC[60]=960; OP_OH[60]=7; OP_OW[60]=7;  // PW features.17.conv.2
        OP_OPCODE[61]=2; OP_OC[61]=1280; OP_IC[61]=320; OP_OH[61]=7; OP_OW[61]=7;  // PW features.18.0
        OP_OPCODE[62]=5; OP_OC[62]=1280; OP_IC[62]=1280; OP_OH[62]=1; OP_OW[62]=1;  // GAP avgpool
        OP_OPCODE[63]=6; OP_OC[63]=4; OP_IC[63]=1280; OP_OH[63]=1; OP_OW[63]=1;  // LINEAR classifier.1
    end
endtask

// $readmemh needs a literal, so this is a case rather than a string array.
task automatic load_golden(input integer k);
    begin
        case (k)
        0: $readmemh("../../software/golden/image_1/001_features_0_0.hex", gold_mem);
        1: $readmemh("../../software/golden/image_1/002_features_1_conv_0_0.hex", gold_mem);
        2: $readmemh("../../software/golden/image_1/003_features_1_conv_1.hex", gold_mem);
        3: $readmemh("../../software/golden/image_1/004_features_2_conv_0_0.hex", gold_mem);
        4: $readmemh("../../software/golden/image_1/005_features_2_conv_1_0.hex", gold_mem);
        5: $readmemh("../../software/golden/image_1/006_features_2_conv_2.hex", gold_mem);
        6: $readmemh("../../software/golden/image_1/007_features_3_conv_0_0.hex", gold_mem);
        7: $readmemh("../../software/golden/image_1/008_features_3_conv_1_0.hex", gold_mem);
        8: $readmemh("../../software/golden/image_1/009_features_3_conv_2.hex", gold_mem);
        9: $readmemh("../../software/golden/image_1/010_features_3_add.hex", gold_mem);
        10: $readmemh("../../software/golden/image_1/011_features_4_conv_0_0.hex", gold_mem);
        11: $readmemh("../../software/golden/image_1/012_features_4_conv_1_0.hex", gold_mem);
        12: $readmemh("../../software/golden/image_1/013_features_4_conv_2.hex", gold_mem);
        13: $readmemh("../../software/golden/image_1/014_features_5_conv_0_0.hex", gold_mem);
        14: $readmemh("../../software/golden/image_1/015_features_5_conv_1_0.hex", gold_mem);
        15: $readmemh("../../software/golden/image_1/016_features_5_conv_2.hex", gold_mem);
        16: $readmemh("../../software/golden/image_1/017_features_5_add.hex", gold_mem);
        17: $readmemh("../../software/golden/image_1/018_features_6_conv_0_0.hex", gold_mem);
        18: $readmemh("../../software/golden/image_1/019_features_6_conv_1_0.hex", gold_mem);
        19: $readmemh("../../software/golden/image_1/020_features_6_conv_2.hex", gold_mem);
        20: $readmemh("../../software/golden/image_1/021_features_6_add.hex", gold_mem);
        21: $readmemh("../../software/golden/image_1/022_features_7_conv_0_0.hex", gold_mem);
        22: $readmemh("../../software/golden/image_1/023_features_7_conv_1_0.hex", gold_mem);
        23: $readmemh("../../software/golden/image_1/024_features_7_conv_2.hex", gold_mem);
        24: $readmemh("../../software/golden/image_1/025_features_8_conv_0_0.hex", gold_mem);
        25: $readmemh("../../software/golden/image_1/026_features_8_conv_1_0.hex", gold_mem);
        26: $readmemh("../../software/golden/image_1/027_features_8_conv_2.hex", gold_mem);
        27: $readmemh("../../software/golden/image_1/028_features_8_add.hex", gold_mem);
        28: $readmemh("../../software/golden/image_1/029_features_9_conv_0_0.hex", gold_mem);
        29: $readmemh("../../software/golden/image_1/030_features_9_conv_1_0.hex", gold_mem);
        30: $readmemh("../../software/golden/image_1/031_features_9_conv_2.hex", gold_mem);
        31: $readmemh("../../software/golden/image_1/032_features_9_add.hex", gold_mem);
        32: $readmemh("../../software/golden/image_1/033_features_10_conv_0_0.hex", gold_mem);
        33: $readmemh("../../software/golden/image_1/034_features_10_conv_1_0.hex", gold_mem);
        34: $readmemh("../../software/golden/image_1/035_features_10_conv_2.hex", gold_mem);
        35: $readmemh("../../software/golden/image_1/036_features_10_add.hex", gold_mem);
        36: $readmemh("../../software/golden/image_1/037_features_11_conv_0_0.hex", gold_mem);
        37: $readmemh("../../software/golden/image_1/038_features_11_conv_1_0.hex", gold_mem);
        38: $readmemh("../../software/golden/image_1/039_features_11_conv_2.hex", gold_mem);
        39: $readmemh("../../software/golden/image_1/040_features_12_conv_0_0.hex", gold_mem);
        40: $readmemh("../../software/golden/image_1/041_features_12_conv_1_0.hex", gold_mem);
        41: $readmemh("../../software/golden/image_1/042_features_12_conv_2.hex", gold_mem);
        42: $readmemh("../../software/golden/image_1/043_features_12_add.hex", gold_mem);
        43: $readmemh("../../software/golden/image_1/044_features_13_conv_0_0.hex", gold_mem);
        44: $readmemh("../../software/golden/image_1/045_features_13_conv_1_0.hex", gold_mem);
        45: $readmemh("../../software/golden/image_1/046_features_13_conv_2.hex", gold_mem);
        46: $readmemh("../../software/golden/image_1/047_features_13_add.hex", gold_mem);
        47: $readmemh("../../software/golden/image_1/048_features_14_conv_0_0.hex", gold_mem);
        48: $readmemh("../../software/golden/image_1/049_features_14_conv_1_0.hex", gold_mem);
        49: $readmemh("../../software/golden/image_1/050_features_14_conv_2.hex", gold_mem);
        50: $readmemh("../../software/golden/image_1/051_features_15_conv_0_0.hex", gold_mem);
        51: $readmemh("../../software/golden/image_1/052_features_15_conv_1_0.hex", gold_mem);
        52: $readmemh("../../software/golden/image_1/053_features_15_conv_2.hex", gold_mem);
        53: $readmemh("../../software/golden/image_1/054_features_15_add.hex", gold_mem);
        54: $readmemh("../../software/golden/image_1/055_features_16_conv_0_0.hex", gold_mem);
        55: $readmemh("../../software/golden/image_1/056_features_16_conv_1_0.hex", gold_mem);
        56: $readmemh("../../software/golden/image_1/057_features_16_conv_2.hex", gold_mem);
        57: $readmemh("../../software/golden/image_1/058_features_16_add.hex", gold_mem);
        58: $readmemh("../../software/golden/image_1/059_features_17_conv_0_0.hex", gold_mem);
        59: $readmemh("../../software/golden/image_1/060_features_17_conv_1_0.hex", gold_mem);
        60: $readmemh("../../software/golden/image_1/061_features_17_conv_2.hex", gold_mem);
        61: $readmemh("../../software/golden/image_1/062_features_18_0.hex", gold_mem);
        62: $readmemh("../../software/golden/image_1/063_avgpool.hex", gold_mem);
        63: $readmemh("../../software/golden/image_1/065_classifier_1_logits_int16.hex", gold_mem);
        default: $display("  [ERR] no golden vector for op %0d", k);
        endcase
    end
endtask
